### ISSUE TITLE
Explosives bypass explosion protection from FTB utilities

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#11]
So they can be used to grief :P
Might need to fire a event when exploding

**Comment by wormzjl** [comment]
Also I think it's good to have a explosion strength in the config.....

**Comment by Foghrye4** [comment]
@wormzjl they probably will not now (0.620).
Explosion power base is added to config.

**Comment by wormzjl** [comment]
Thx!


2017年2月18日 19:58，"Foghrye4" <notifications@github.com>写道：
