### ISSUE TITLE
Item put on the right side of the chemically resistant oven is not consumed

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#12]
This will be consumed
![image](https://cloud.githubusercontent.com/assets/2989009/23103534/c118cb50-f6bc-11e6-927c-840882506939.png)

This will not
![image](https://cloud.githubusercontent.com/assets/2989009/23103541/cc228658-f6bc-11e6-94d9-870c9bd9b6c1.png)

**Comment by wormzjl** [comment]
Trying to make sulfuric acid, saltpeter and sulfur are not consumed equivalently
Is there something like chanced based here?
![image](https://cloud.githubusercontent.com/assets/2989009/23103581/3b62c96a-f6bd-11e6-973b-fbcaceee4216.png)

**Comment by wormzjl** [comment]
More bugs: put a whole stack of sodium hydrogen sulfate inside, and you'll get a single piece of sodium sulfate in the end
same for the regeneration of zeolite

**Comment by Foghrye4** [comment]
Fixed in 0.621

**Comment by wormzjl** [comment]
New bug incoming
While making mercury, the first cinnabar dust put inside an empty oven is not consumed
Same for sulfuric acid, the first sulfur dust is not consumed, but the saltpeter dust is

**Comment by Foghrye4** [comment]
Fixed in 0.622
