### ISSUE TITLE
Sulfuric acid production is broken

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#13]
Probably because of the chimney?
![image](https://cloud.githubusercontent.com/assets/2989009/23103648/e870446a-f6be-11e6-8e17-aefadfd3d6f6.png)
![image](https://cloud.githubusercontent.com/assets/2989009/23103663/1ba56144-f6bf-11e6-8abf-71fa78c39cd4.png)

Here is my testing setup, no sulfuric acid is coming out, and I can't find any SO3 via wailla

**Comment by Foghrye4** [comment]
Brutally fixed in 0.621.

**Comment by wormzjl** [comment]
lol
