### ISSUE TITLE
[suggestion]IC2 upgrade slots for machines

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#18]
Just want to grab some overclocker for late game automations :P

**Comment by Foghrye4** [comment]
Done with overclocker and storage upgrates for both chemical reactors, lab electrolizer and paper machine. If you need something else - ask.

**Comment by wormzjl** [comment]
Transformer upgrade, if one wants to use uncomplication
Also one might need to think twice to "overclock" chemical reactions...
Maybe let the reactor explode or just trash the reagents due to thermal runaway if it runs out of power?
