### ISSUE TITLE
IHL oil generation is weird.

### ISSUE THREAD

**Issue by indoorsNB** [Foghrye4/ihl#19]
I installed the RTG, BC, IHL and other mods, and the build craft oil generate under ocean is very weird. after I removed the build craft- energy and delete the map, on same position it generated the IHL oil
So I think it is a IHL bug. :( 
https://github.com/indoorsNB/tuchuang/raw/master/0%2C-1.png

**Comment by indoorsNB** [comment]
I already set    ` B:generateOil=false`

**Comment by indoorsNB** [comment]
I go check the changelog, I found this `- 0.623 - Oregen is rewritten.`

**Comment by Foghrye4** [comment]
Is a black pixels on a picture an oil blocks?
Those regular structures compounded from clay and oil blocks?
Had I fixed title of this issue correctly?

If you mean that oil generation is fine, but too regular, that probably incorrect random seed function fault.

**Comment by indoorsNB** [comment]
The oil is generated too much under water/ land. You can see the darker pixel under water. These are oil.
I have no idea why my whole map generate these oil wells everywhere, they are all straight  to the bedrock and regular ( repeat generate on at least 10 chunks.) I can find many ore in oil well. 🔵=water/gregtech sea water
⬛️=bedrock
⚫️=oil
🔶=dirt/stone
❌=ore
I'm not sure how to explain it (because I'm bad at english )
In ocean, it looks like this
🔵🔵🔵🔵🔵🔵🔵
🔵🔵🔵🔵🔵🔵🔵
🔵🔵🔵🔵🔵🔵🔵
🔵🔵🔵🔵🔵🔵🔵
🔵🔵🔵🔵🔵🔵🔵
🔶🔶⚫️⚫️⚫️🔶🔶
❌🔶⚫️❌⚫️🔶🔶
🔶🔶⚫️⚫️⚫️❌🔶
❌🔶⚫️❌❌❌🔶
🔶🔶❌⚫️⚫️🔶❌
⬛️⬛️⬛️⬛️⬛️⬛️⬛️
On land, it became like this
🔶🔶🔶🔶🔶🔶🔶🔶🔶
🔶🔶🔶🔶🔶🔶🔶🔶🔶
❌🔶🔶🔶❌🔶🔶🔶❌
🔶🔶❌⚫️⚫️🔶🔶🔶🔶
❌🔶⚫️❌⚫️🔶❌🔶❌
🔶❌⚫️⚫️⚫️🔶🔶🔶🔶
🔶❌⚫️❌⚫️🔶❌🔶🔶
🔶🔶❌⚫️❌🔶🔶🔶🔶
❌🔶⚫️⚫️⚫️🔶🔶🔶🔶
⬛️⬛️⬛️⬛️⬛️⬛️⬛️⬛️⬛️

**Comment by indoorsNB** [comment]
I also found some very strange ore gen. IHL ores more like to generate like a 'T' or a 'l'
I don't know what cause that problem.
https://github.com/indoorsNB/tuchuang/raw/master/2017-03-20_19.22.25.png

**Comment by Foghrye4** [comment]
Summary - too much oil and too regularly. Understood.

**Comment by Foghrye4** [comment]
Oil now replace only lava blocks. Also I changed a way how random seed is generated.

**Comment by indoorsNB** [comment]
Salt water generate still weird :( they like to generate like a square, not a lake. 
https://github.com/indoorsNB/tuchuang/raw/master/2017-03-23_23.04.16.png

**Comment by Foghrye4** [comment]
This is how it is now: ![Imgur](http://i.imgur.com/mclixKu.png)

**Comment by indoorsNB** [comment]
oil is still werid, I think you forgot netherworld have lava https://github.com/indoorsNB/tuchuang/raw/master/2017-04-01_20.09.04.png

**Comment by Foghrye4** [comment]
Yep, I forgot. Oil now formed inside hollow obsidian columns.
![Imgur](http://i.imgur.com/DXp8JS7.jpg)

**Comment by indoorsNB** [comment]
XD
But Buildcraft oil will blowup in nether

**Comment by indoorsNB** [comment]
When build craft installed, IHL will generate BC oil(ｰ ｰ;)

**Comment by Foghrye4** [comment]
^_^ Ha! Whenever you destroy obsidian block near oil block everything is blown up. Looks fun. Maybe keep it as is?

**Comment by indoorsNB** [comment]
sounds good XD

**Comment by indoorsNB** [comment]
Hmm, when I choose flat world, I think something bad is happening.....
Obsidian everywhere
(Open a new world, LOL)

**Comment by Foghrye4** [comment]
Fixed.
