### ISSUE TITLE
[Suggestion] A fluid flow controller block

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#22]
One problem I've encountered while dealing with chemistry automation is to control the amount of different fluids input to prevent completely filling it up

Buildcraft pipe + gate could be helpful, but the precision is a problem

So I think that we need a fluid flow control block (dosing pump?), that sends a desired amount of fluid pass upon receiving a redstone signal (or similar mecanisms)

**Comment by Foghrye4** [comment]
Good idea.

**Comment by Foghrye4** [comment]
Done
![Imgur](http://i.imgur.com/0veVLUZ.png)

**Comment by wormzjl** [comment]
nice one
