### ISSUE TITLE
0.629 breaks terrafirmacraft's rendering

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#27]
Probably also some other mods..
with 0.628:
![image](https://cloud.githubusercontent.com/assets/2989009/25071307/fb8e9076-22b3-11e7-9a0a-424383d2bf14.png)

0.629:
![image](https://cloud.githubusercontent.com/assets/2989009/25071334/8509fdae-22b4-11e7-9f81-b223fb481f13.png)

**Comment by Foghrye4** [comment]
Lighting devices and coremod removed due to incompatibility with TerraFirmaCraft. Everything should be fine now.

**Comment by wormzjl** [comment]
seems fine through...
