### ISSUE TITLE
Mirror crash

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#29]
On placing, seems a bit random
https://pastebin.com/pWsbSnpC

**Comment by Foghrye4** [comment]
Lighting devices and coremod removed due to incompatibility with TerraFirmaCraft. I checked mirror and currently its working fine, but a problem could be caused by reflecting one certain Tile Entity from TFC.

**Comment by wormzjl** [comment]
this crash happens without tfc

**Comment by Foghrye4** [comment]
Hmm... do it happened with 0.631? http://www.mediafire.com/file/7uae8vel4eo8h1o/ihl-tools_n_machines-0.631-1.7.10.jar

**Comment by wormzjl** [comment]
this thing is too random...haven't be able to repeat it
