### ISSUE TITLE
Fluids messed up with ic2 universal cell, compatibility issue with techreborn

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#3]
![2](https://cloud.githubusercontent.com/assets/2989009/22401096/d050781c-e5c7-11e6-91b0-5e8fd927b5c8.png)
Tries to put some universal fluid cell into a paper machine with pulp inside but it gives me Beryllium and iron buckets

**Comment by wormzjl** [comment]
Could be other mods messing it up...still investigating

**Comment by wormzjl** [comment]
Has to reopen this issue, because this happens and only happens with both ihl and techreborn installed

**Comment by Foghrye4** [comment]
That's cool. Only paper machine? Other machines are ok? Try it with chemical reactor and bronze tub.

**Comment by wormzjl** [comment]
Same for all fluid containers, including buildcraft and railcraft
For example shift rightclick a bc tank with any universal fluid cell will give Beryllium...and a empty bucket

**Comment by Foghrye4** [comment]
@wormzjl it's definitely something like 
```
if (FML.isModLoaded("ihl")) {
       this.fuckUpIC2UnivesalCells();
}
```

**Comment by wormzjl** [comment]
Mind take a look at this?
https://github.com/TechReborn/TechReborn/blob/1.7.10/src/main/java/techreborn/items/ItemCells.java#L28

I have no idea why putting both mod together would cause such a problem :P

**Comment by Foghrye4** [comment]
@wormzjl as for IC2 universal fluid cells while drained dry they simple remove NBT tag of fluid from itself. There is no way this operation could change item ID (normally). Care to put cells into "Ore dictionary item scanner" to check if they are still IC2 ones? Also put a bucket and check item class of it as well.

**Comment by wormzjl** [comment]
![1](https://cloud.githubusercontent.com/assets/2989009/22406234/9b75bb88-e64f-11e6-8d2a-4b0f10c1e2f1.png)
yes they are

**Comment by Foghrye4** [comment]
@wormzjl have no ideas then.

**Comment by wormzjl** [comment]
Don't know much about coding, but could these 2 conflict?
https://github.com/Foghrye4/ihl/blob/master/ihl/processing/invslots/InvSlotConsumableLiquidIHL.java#L37

https://github.com/TechReborn/TechReborn/blob/1.7.10/src/main/java/techreborn/items/ItemCells.java#L152

**Comment by Foghrye4** [comment]
@wormzjl no. Bug could occur if universal cells registered as fluid container in FluidContainerRegistry, but this is not happened as long as I check in TechReborn.

**Comment by wormzjl** [comment]
Oops, there is something wrong with my tests

Apparently there is no problem draining these cells in railcraft tanks

Doing further testing...

**Comment by wormzjl** [comment]
Did some extensive testing with all fluid tanks I got

IHL machines:
Insert cell through GUI: bugged
Shift + rightclick with cell: Normal

IC2 fluid/solid canning machine:
Insert cell through GUI: bugged
Shift + rightclick with cell: Normal

Buildcraft tank:
Shift + rightclick with cell: bugged

Immersive engineering tank:
Shift + rightclick with cell: bugged

Raicraft tank and tankcart:
Insert cell through GUI: Normal
Shift + rightclick with cell: Normal

Advanced rocketry tank:
Insert cell through GUI: bugged
Shift + rightclick with cell: normal

Open blocks tank:
Shift + rightclick with cell: normal

Rotarycraft reservoir:
Shift + rightclick with cell: normal

Pressure pipes tank:
Insert cell through GUI: bugged

**Comment by wormzjl** [comment]
Bug on techreborn's side, thanks for looking through :D
