### ISSUE TITLE
Some recipes are not in GT machines (IC machines are too expensive)

### ISSUE THREAD

**Issue by indoorsNB** [Foghrye4/ihl#31]
hmm, dustBrick is not allow to make in GT6 machine, it is strange. 
I'm not sure other dust or something have recipe in GT machines.
maybe Greg will add it?

**Comment by indoorsNB** [comment]
Someone here?

**Comment by Foghrye4** [comment]
Where?

**Comment by indoorsNB** [comment]
brickdust is not in gt6 machine, ic only

**Comment by Foghrye4** [comment]
Use ceramic dust from GT6 as replacement.

**Comment by indoorsNB** [comment]
I'm sure it don't have any kinds of recipe in gt can make ceramic dust

**Comment by Foghrye4** [comment]
Shredder now shred bricks to ceramic dust.
