### ISSUE TITLE
Sulfate acid is uncraftable 

### ISSUE THREAD

**Issue by yqmtat** [Foghrye4/ihl#39]
Unless use buildcraft pipes at every junction between the machines

**Comment by yqmtat** [comment]
It is a problem about liquid transmission, so that you can't place a machine right beside the receiving machine, most fluid may lost rather than get into the receiving machine, thus little liquid is accumulated for further reaction.

**Comment by Foghrye4** [comment]
Probably outdated IHL again. This process was radically simplified in latest versions. 
![Imgur](http://i.imgur.com/setdKPz.png)

Sorry for a late answer.
