### ISSUE TITLE
Some machines does not use power with uncomplication mod

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#4]
Tested with no actual power use:
Laboratory electrolyzer
Paper machine
Wooden rolling machine
rotary pump
fluidized bed reactor
Cryogenetic distiller
...Almost everything

Tested with actual power use:
Muffle furnace
Acheson furnace
Electric evaporator

**Comment by Foghrye4** [comment]
@wormzjl 
What do you mean by "does not use power"?
* They don't drain power from IC2 energy net?
* They don't drain power from flexible cables energy net?
* They operate without energy?
* They don't use RF?
![lab_electrolizer](http://i.imgur.com/PXw5Mc2.png)

**Comment by wormzjl** [comment]
Ok found out the issue, it seems that ihl does not work well with uncompliication mod which restores the old e-net, could you take a look at this?

Also the energy use to electrolyze water seems to be a bit low for me..

**Comment by Foghrye4** [comment]
I have no trouble with this mod http://forum.industrial-craft.net/index.php?page=Thread&threadID=11586&pageNo=1 at all. How I could repeat mentioned bug?

**Comment by wormzjl** [comment]
Connect the machine with a batbox, and you'll see that the power does not drop at all in the batbox

If you put battery directly inside the machine it actually drains power

**Comment by wormzjl** [comment]
Update: These machines only consumes power when there is no external power source connected -.-

**Comment by Foghrye4** [comment]
> - 0.614 - Fixed missing rubber tree sap block. Fixed compatibility with Uncomplicated addon. Fixed sodium sulfate tooltip. Most of machines now consume 10x energy, Lab electrolizer 100x energy per tick.

**Comment by wormzjl** [comment]
Ahh thx :D, works like a charm
