### ISSUE TITLE
Iron workbench caused crash

### ISSUE THREAD

**Issue by yuyuyzl** [Foghrye4/ihl#49]
Crash report on pastebin: https://pastebin.com/sDJjKsX0

I was trying to craft nut M10 with some other things (sand, clay dust and so on) in the table, after i clicked the button i saw 2 items processing instead of one, just like when you craft the wooden rolling machine, and it crashed with all my things disappeared. Then i retried with a new one, but this time it's fine.

Wondering if you can figure out how that happened. Now i'm trying to keep the table as clean as i could to prevent crash like that.

**Comment by Foghrye4** [comment]
I have no idea why this was happened, but to prevent such bug in a future I have add additional !=null check for recipe output in 0.637.
