### ISSUE TITLE
Cryogenic distiller bug

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#5]
![image](https://cloud.githubusercontent.com/assets/2989009/22523805/fa48e04a-e8c0-11e6-8251-416e24131fe0.png)
The machine works normally with nothing conncected

![2017-02-01_20 58 54](https://cloud.githubusercontent.com/assets/2989009/22523897/533c40de-e8c1-11e6-91ba-2077bdbbcb62.png)
When connected to pipes, it outputs nitrogen, but no oxygen, and the machine stopped working after one cycle

![2017-02-01_21 01 18](https://cloud.githubusercontent.com/assets/2989009/22523975/a32a1256-e8c1-11e6-81e7-3626c92bfe62.png)
Waila info
![image](https://cloud.githubusercontent.com/assets/2989009/22523997/afc13a76-e8c1-11e6-9a99-0dc3bfc8d20e.png)
However there is no oxygen in the GUI

Some issue with the side of input/output?

**Comment by wormzjl** [comment]
![image](https://cloud.githubusercontent.com/assets/2989009/22524152/7326f276-e8c2-11e6-959b-4316da9f2a41.png)

Also I think distillation air should use much more power than this

**Comment by Foghrye4** [comment]
Fixed in 0.616. Dismount and mount distiller back to see changes,

**Comment by wormzjl** [comment]
seems good now
