### ISSUE TITLE
adding recipes with three kinds of liquid in reactors

### ISSUE THREAD

**Issue by yuyuyzl** [Foghrye4/ihl#54]
May i ask if i can add some recipes with 3 or more kinds of liquid? We are trying to produce tnt using toluene and 2 acid, but in game the recipe is shown(incorrectly) in nei but will not work. 
I wonder if it's a bug or we just cannot add recipes with 3 liquids.

**Comment by yuyuyzl** [comment]
this is what we write in the config:

addrecipe
(
chemicalreactor,
recipeinput(fluidstack(toluene,500),fluidstack(sulfuricacid,500),fluidstack(nitricacid,500)),
recipeoutput(itemstack(capptfc:chemicals,1,16))
)

**Comment by Foghrye4** [comment]
Should work fine now. Check it with 0.639.

**Comment by wormzjl** [comment]
The recipe seems to be working now.
However the NEI handler does not allow more than 2 input fluids to be shown up.
Is there any way to make it work with more products? thanks!

**Comment by Foghrye4** [comment]
Yes. NEI GUI fixed. (0.641)

**Comment by wormzjl** [comment]
awsome

**Comment by yuyuyzl** [comment]
yup awesome
and thanks XD
