### ISSUE TITLE
Reflux condenser issue

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#56]
So I've add some custom frictionner recipes with custom fluids added by customstuff mod, but the recipes does not work.
After looking at the code I found that there is some sort of temperature check, while I'm unable to set the temperature for my custom fluid.
Could you add some method to bypass this?

**Comment by Foghrye4** [comment]
Boiling point of unknown by IHL fluids are now 373 K (0.642). Tell me if this helps.

**Comment by wormzjl** [comment]
![image](https://cloud.githubusercontent.com/assets/2989009/26561898/41d87aee-44c2-11e7-9834-854157b36cee.png)

seems good now, but is it normal to have some water in the column?
Also does it work like more section->better speed->less energy consumption?

**Comment by yuyuyzl** [comment]
sorry but this is not fixed.

**Comment by wormzjl** [comment]
nope...problem still persists...might be related to density/boiling point?
what does this temperature check serves actually?

**Comment by Foghrye4** [comment]
@wormzjl it checks if fluid can be condensed using normal temperature water. Water in a column because everything is calculated from a single tileentity, including condensation process. Does column work fine with normal oil (with IHL native recipe)?

**Comment by wormzjl** [comment]
normal oil is fine, the problem occurs only with my custom fluids

**Comment by Foghrye4** [comment]
@wormzjl I would like to know what you want to process.

**Comment by wormzjl** [comment]
http://i.imgur.com/MmDTHyG.jpg
this

**Comment by Foghrye4** [comment]
Wow. But where is column? IHL distiller?

**Comment by wormzjl** [comment]
yep

**Comment by Foghrye4** [comment]
IHL fractionator cannot condense anything with boiling point above temperature of coolant (water in that case). Also it cannot output gases, only fluids. It will not work for helium. To separate gases you need to use cryogenic distiller instead. I can simplify it and turn it in another simple reactor. It will consume water and output anything independent from temperatures. Currently it is a crude simulation of real life fractionator and it using real physic calculations.

**Comment by wormzjl** [comment]
The problem with simulation in minecraft is that you need some gameplay element behind it, or people will not notice its existence.
How do you determine the boiling point?

**Comment by Foghrye4** [comment]
@wormzjl I just set it for my fluids. For others before update it is here: https://github.com/Foghrye4/ihl/blob/master/ihl/worldgen/ores/IHLFluid.java#L118

**Comment by Foghrye4** [comment]
@wormzjl so, should I do it? I mean - remove all physic stuff and turn it to a plane simple crafting device?

**Comment by wormzjl** [comment]
Umm, for now I think it's probably better to make it simpler, as currently nobody really uses the fluid temperature and density system. If you want to do simulation, you will need a whole system supporting it
