### ISSUE TITLE
IHLTank with 0mB of liquid

### ISSUE THREAD

**Issue by yuyuyzl** [Foghrye4/ihl#57]
When you use pipes to insert some other kinds of liquid to a full IHL tank, you will found a 0mB fluid stack inside the tank and that will block any extraction because it cannot be removed.

**Comment by yuyuyzl** [comment]
![image](https://user-images.githubusercontent.com/14276008/27044848-9e3a2a52-4fd1-11e7-99f7-506a9ae99e19.png)

**Comment by Foghrye4** [comment]
Fixed probably (0.646). Unfortunately you need to redeploy this reactor to fix it. But If I did everything right this will not happened again.

**Comment by yuyuyzl** [comment]
GJ. Thanks.
