### ISSUE TITLE
Laboratory electrolyzer and fluidized bed reactor need a fluid output port

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#6]
to automate stuffs via pipe

**Comment by Foghrye4** [comment]
WTF is "fluid output port"?

**Comment by wormzjl** [comment]
Like the air distiller, so we can use pipes to extract the products

**Comment by Foghrye4** [comment]
You mean in current version you can't? What mod with pipes do you use? If GT6, then install pump on a pipe near device and set it to drain fluid from device. An air distiller and a rubber tree sap gathering sack in an only devices, that able to "autooutput" fluids.

**Comment by wormzjl** [comment]
tried with magneticraft, gonna do more testing later..

**Comment by wormzjl** [comment]
Ok seems that there is a side for extraction...
