### ISSUE TITLE
NEI issue with chemical reactors

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#62]
So if you have a reagent with less than 1000 mb, the recipe will be shown correctly in NEI.
But if the fluid amount is between 1000 and 2000 mb, problem apprears.
Like the one producing calcium chloride from HCl and limemilk, it shows as using 1000 mb of each product, but actually uses 1334 and 1667 mb respectively.
Since this would lead to some misunderstanding for players, I'd suggest show the recipe in NEI just like this with a specific amount.
![image](https://user-images.githubusercontent.com/2989009/27262470-d738d062-5457-11e7-85fa-9da58d4d8d63.png)

**Comment by wormzjl** [comment]
Also another bug, this reaction will not work with exactly 1334 mb of HCl and 1667 mb of limemilk inside, you need two bucket of each product to start the reaction but the consumption is correct.

**Comment by Foghrye4** [comment]
Fixed this way:
![Imgur](http://i.imgur.com/3CzMJCO.png)

**Comment by wormzjl** [comment]
lol nice
