### ISSUE TITLE
[suggestion] prevent the cryo distiller from distilling air if the entry side is blocked

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#63]
Which is this side
![image](https://user-images.githubusercontent.com/2989009/27299449-b8e6519a-552c-11e7-9db0-b7c227d52150.png)

The problem I have encountered is that when I used it in something other than air distillation, when the input product used up it will mess up the whole system by introducing oxygen and nitrogen into the pipes.

**Comment by wormzjl** [comment]
Also it does not stop working even full (again :P)

**Comment by Foghrye4** [comment]
Done.
