### ISSUE TITLE
Can't use "used" Flint&steel on IHL Explosive Pack 

### ISSUE THREAD

**Issue by yuyuyzl** [Foghrye4/ihl#64]
Only minecraft:flint_and_steel:0 will do but then the lighter got damaged and then you need to make a new one.
Fix plz.

**Comment by Foghrye4** [comment]
Fixed.

**Comment by Foghrye4** [comment]
Also if there is an other devices, who could serve a same purpose, I could add it as well. Or you can do it using Minetweaker (add them to ore dictionary entry "toolLighter").

**Comment by yuyuyzl** [comment]
gj, thx
