### ISSUE TITLE
AIOOB with FBR

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#65]
Log
https://pastebin.com/RBvTxTAY

With this recipe:

```
addrecipe
(
fluidizedbedreactor,
recipeinput(fluidstack(hydrogensulfide,1000),fluidstack(oxygen,500)),
recipeoutput(itemstack(terrafirmacraft:item.Powder,1,3))
)
```

**Comment by Foghrye4** [comment]
Fixed, but its weird that you are using FBR for two fluid inputs. Using FBR IRL unnecessary in that case.
Also 2xH2S+3xO2 > 2xH2O + 2xSO2 > 2xH2SO3. Those are fluids or gases depending from conditions, but normally never solid substances.

**Comment by wormzjl** [comment]
It's from here, but yeah I should use the normal reactor
https://en.wikipedia.org/wiki/Claus_process
