### ISSUE TITLE
FBR catalyst issue

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#66]
When upgrading from 652 to 653, my players has reported that the catalyst consumption in the FBR has increased significantly.
Also, if you put a whole stack of catalyst in, the entire stack will be consumed instead of one.
And, is it possible to add a config option to adjust catalyst consumption rate, or to specify them in the recipe definition?
Thank you.

**Comment by Foghrye4** [comment]
I made a silly mistake when I have fixed FBR code. I forgot to set NBT tag to 0 when item removed from catalyst stack. Fixed. Also I added a config option "maxCatalystUses". "1000" by default, which means every 1000 reaction one item from stack will be consumed.
