### ISSUE TITLE
Machine fluid output issue

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#69]
For example, if I connect pipe to a cryogenic distiller which is distillating air, the oxygen output port could output both nitrogen and oxygen, and my pipe could get blocked by the mixed output.
I think I've encountered similar problems with chemical reactor and FBR, If I got 2 fluid outputs, they cannot be extracted from the machine with a constant direction.

**Comment by Foghrye4** [comment]
That is a flaw of a tank, which able to store unlimited types of fluid at once. When you fully drain a lightest fluid you eventually start to drain next fluid.

**Comment by wormzjl** [comment]
I think there could be some workarounds.
Like, adding an advanced fluid regulator block that is able to sort and distribute fluids, with some sort of whitelist on input or output on each sides.
Buildcraft diamond fluid pipe can sort fluids, but it cannot prevent undesired fluids from entering.

**Comment by Foghrye4** [comment]
I made automatic separator.
http://www.mediafire.com/file/1yl29ugu8986q1p/ihl-tools_n_machines-0.656-1.7.10.jar

**Comment by wormzjl** [comment]
So this is like a decanter, great!
