### ISSUE TITLE
Silicon production method

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#7]
Just in case you care with the details
2MgO(s) + Si(s) + 2CaO(s) → 2Mg(g) + Ca2SiO4(s)

But in the game it's the reverse?

**Comment by Foghrye4** [comment]
Its a different reaction.
See: https://en.wikipedia.org/wiki/Magnesium_silicide

**Comment by wormzjl** [comment]
With excess magnesium yes...
But IMO this is still not the method to make silicon

**Comment by Foghrye4** [comment]
@wormzjl it is an ancient method of obduction of silicon. And an only option if you have no a high-temperature ore-smelting furnace. To use coke to obtain silicon from SiO2 you need a temperature up to 1800 degrees, which cannot be gained with muffle furnace.

**Comment by Foghrye4** [comment]
Recipe removed in 0.621.
