### ISSUE TITLE
Muffle furnace issues

### ISSUE THREAD

**Issue by wormzjl** [Foghrye4/ihl#8]
Problem 1: Put one stack of NaOH and one stack of bauxite dust inside, after processing there is 1 stack of Sodium aluminate and 63 bauxite dust

Problem 2: This device is very difficult to automate, as it cannot handle the excess of 1 input product, which will fill both slots. 

I'd also suggest to separate the input and output part for the sake of automation

**Comment by wormzjl** [comment]
Ok got a new issue here...
1 stack of iron oxide + 1 stack of lithium oxide=
![image](https://cloud.githubusercontent.com/assets/2989009/22849758/5b77627e-f000-11e6-8084-d983894c659b.png)
When taken out, it became a single dust

**Comment by Foghrye4** [comment]
Latest changes in 0.619 should fix that.

**Comment by wormzjl** [comment]
Seems good to me
Could you update the source on github by the way? I might be able to help with some small bugs

**Comment by Foghrye4** [comment]
Done.

**Comment by wormzjl** [comment]
Have to open this issue again...
![image](https://cloud.githubusercontent.com/assets/2989009/23102847/fa776e12-f6b0-11e6-91dd-ed554d039fe0.png)
to
![image](https://cloud.githubusercontent.com/assets/2989009/23102850/0f230042-f6b1-11e6-8bf7-ed0164210d28.png)

while on NEI
![image](https://cloud.githubusercontent.com/assets/2989009/23102859/4089019a-f6b1-11e6-915d-f4ba6994359d.png)

**Comment by Foghrye4** [comment]
Fixed in 0.621.
